sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: your_username
    password: your_password
  alioss:
    endpoint: your-oss-endpoint.aliyuncs.com
    access-key-id: your_access_key_id
    access-key-secret: your_access_key_secret
    bucket-name: your_bucket_name
  redis:
    host: localhost
    port: 6379
    password: your_redis_password
    database: 10
  wechat:
    appid: your_appid
    secret: your_secret
    mchid: your_mchid
    mchSerialNo: your_mchSerialNo
    privateKeyFilePath: /path/to/your/private_key.pem
    apiV3Key: your_api_v3_key
    weChatPayCertFilePath: /path/to/your/wechatpay_cert.pem
    notifyUrl: https://your-domain.com/notify/paySuccess
    refundNotifyUrl: https://your-domain.com/notify/refundSuccess
